In [3]:
import pandas as pd

df = pd.read_csv("resultados_experimentacion.csv")
df.head()

,problema,n,k,algoritmo,status,synthesis_time_ms,max_memory_mb,expanded_states,used_states,expanded_transitions,used_transitions,heuristic_time_ms
0,AT,1,1,MonolithicController,OK,6.0,9.56,6.0,6.0,8.0,8.0,0.0
1,AT,1,1,DirectedController,OK,39.0,15.41,6.0,6.0,8.0,8.0,1.0
2,AT,1,1,PORController,OK,31.0,15.41,6.0,6.0,8.0,8.0,0.0
3,AT,1,1,PORGeneralizedController,OK,30.0,10.95,6.0,6.0,8.0,8.0,0.0
4,AT,1,2,MonolithicController,OK,2.0,9.55,7.0,7.0,10.0,9.0,0.0

In [6]:
k = 6  # cambiá este valor

df_k = df[df["k"] == k]
tabla = df_k.pivot_table(index="n", columns="algoritmo", values="max_memory_mb")
tabla

algoritmo,DirectedController,MonolithicController,PORController,PORGeneralizedController
n,,,,
1,15.97,9.57,17.12,11.80
2,19.69,11.45,12.81,15.54
3,25.51,20.24,42.61,12.87
4,97.21,141.11,104.70,64.56
5,238.13,1413.12,968.13,366.59
6,2191.36,NaN,NaN,3235.84